#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/all-projects/page/:num"

collections:
  publications:
    output: true
    permalink: /:collection/:name

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: '_posts'
    values:
      permalink: /all-projects/:slug

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

gems: ['jekyll/scholar']

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------
scholar:
  style: apa
  locale: en

  sort_by: none
  order: descending

  source: ./_bibliography
  bibliography: papers.bib
  bibliography_template: bibtemplate 

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  repository: /publications
  repository_file_delimiter: "." 
  
  query: "@*"